apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dplj3sal8-java-springboot-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/dplj3sal8-java-springboot